require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoardingCardsController do

  # This should return the minimal set of attributes required to create a valid
  # BoardingCard. As you add validations to BoardingCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoardingCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all boarding_cards as @boarding_cards" do
      boarding_card = BoardingCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:boarding_cards).should eq([boarding_card])
    end
  end

  describe "GET show" do
    it "assigns the requested boarding_card as @boarding_card" do
      boarding_card = BoardingCard.create! valid_attributes
      get :show, {:id => boarding_card.to_param}, valid_session
      assigns(:boarding_card).should eq(boarding_card)
    end
  end

  describe "GET new" do
    it "assigns a new boarding_card as @boarding_card" do
      get :new, {}, valid_session
      assigns(:boarding_card).should be_a_new(BoardingCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested boarding_card as @boarding_card" do
      boarding_card = BoardingCard.create! valid_attributes
      get :edit, {:id => boarding_card.to_param}, valid_session
      assigns(:boarding_card).should eq(boarding_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BoardingCard" do
        expect {
          post :create, {:boarding_card => valid_attributes}, valid_session
        }.to change(BoardingCard, :count).by(1)
      end

      it "assigns a newly created boarding_card as @boarding_card" do
        post :create, {:boarding_card => valid_attributes}, valid_session
        assigns(:boarding_card).should be_a(BoardingCard)
        assigns(:boarding_card).should be_persisted
      end

      it "redirects to the created boarding_card" do
        post :create, {:boarding_card => valid_attributes}, valid_session
        response.should redirect_to(BoardingCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boarding_card as @boarding_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoardingCard.any_instance.stub(:save).and_return(false)
        post :create, {:boarding_card => {  }}, valid_session
        assigns(:boarding_card).should be_a_new(BoardingCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoardingCard.any_instance.stub(:save).and_return(false)
        post :create, {:boarding_card => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boarding_card" do
        boarding_card = BoardingCard.create! valid_attributes
        # Assuming there are no other boarding_cards in the database, this
        # specifies that the BoardingCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BoardingCard.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => boarding_card.to_param, :boarding_card => { "these" => "params" }}, valid_session
      end

      it "assigns the requested boarding_card as @boarding_card" do
        boarding_card = BoardingCard.create! valid_attributes
        put :update, {:id => boarding_card.to_param, :boarding_card => valid_attributes}, valid_session
        assigns(:boarding_card).should eq(boarding_card)
      end

      it "redirects to the boarding_card" do
        boarding_card = BoardingCard.create! valid_attributes
        put :update, {:id => boarding_card.to_param, :boarding_card => valid_attributes}, valid_session
        response.should redirect_to(boarding_card)
      end
    end

    describe "with invalid params" do
      it "assigns the boarding_card as @boarding_card" do
        boarding_card = BoardingCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BoardingCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => boarding_card.to_param, :boarding_card => {  }}, valid_session
        assigns(:boarding_card).should eq(boarding_card)
      end

      it "re-renders the 'edit' template" do
        boarding_card = BoardingCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BoardingCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => boarding_card.to_param, :boarding_card => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boarding_card" do
      boarding_card = BoardingCard.create! valid_attributes
      expect {
        delete :destroy, {:id => boarding_card.to_param}, valid_session
      }.to change(BoardingCard, :count).by(-1)
    end

    it "redirects to the boarding_cards list" do
      boarding_card = BoardingCard.create! valid_attributes
      delete :destroy, {:id => boarding_card.to_param}, valid_session
      response.should redirect_to(boarding_cards_url)
    end
  end

end
